### ISSUE TITLE
[BUG] Bug in the suggestion option!

### ISSUE THREAD

**Issue by games4681** [BlueTree242/DiscordSRVUtils#153]
Hello dear plugin developer,
There is a problem with your plugin, it turns out that when I restart the server, it forgets all the votes that people have made and resets the number to one, which causes all the votes that were already made before the restart to be deleted, that is, if I want to confirm a vote through the bot, the bot does not know about the number this proposal because it is not It exists for him, is it possible to arrange that Restart does not delete it from the database of the plugin?

PS The problem also happens in the tickets system
So this makes the plugin less useful for servers that need to do a lot of restarts.

**Comment by BlueTree242** [comment]
What hosting is your server on?

**Comment by games4681** [comment]
self hosting and i do daily restart to reset the memory usage

**Comment by BlueTree242** [comment]
Can you provide these information:

- Server software
- Minecraft Version
- DiscordSRVUtils Version (please use /dsu command)

**Comment by games4681** [comment]
1. paper
2. 1.20.2
3. discordsrvutilis version: 1.2.13

**Comment by BlueTree242** [comment]
Can you provide the database files located in `/plugins/DiscordSRVUtils/database` before and after restart?

**Comment by games4681** [comment]
i can find error:
[06:57:11 INFO]: [DiscordSRVUtils] games14#0000 Used /denysuggestion Command
[06:57:24 WARN]: java.lang.NullPointerException: Cannot invoke "tk.bluetree242.discordsrvutils.DiscordSRVUtils.getMainConfig()" because "core" is null
[06:57:24 WARN]:        at DiscordSRVUtils-1.2.13.jar//tk.bluetree242.discordsrvutils.bukkit.discordsrv.SlashCommandProvider.onCommand(SlashCommandProvider.java:72)
[06:57:24 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[06:57:24 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[06:57:24 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[06:57:24 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.api.ApiManager.invokeMethod(ApiManager.java:344)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.api.ApiManager.handleSlashCommandEvent(ApiManager.java:319)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.api.ApiManager.onSlashCommand(ApiManager.java:293)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:483)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.handleEvent(JDAImpl.java:159)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.InteractionCreateHandler.handleCommand(InteractionCreateHandler.java:75)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:59)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.main(ReadingThread.java:108)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.runMain(ReadingThread.java:64)
[06:57:24 WARN]:        at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.ws.client.WebSocketThread.run(WebSocketThread.java:45)

**Comment by BlueTree242** [comment]
> i can find error: [06:57:11 INFO]: [DiscordSRVUtils] games14#0000 Used /denysuggestion Command [06:57:24 WARN]: java.lang.NullPointerException: Cannot invoke "tk.bluetree242.discordsrvutils.DiscordSRVUtils.getMainConfig()" because "core" is null [06:57:24 WARN]: at DiscordSRVUtils-1.2.13.jar//tk.bluetree242.discordsrvutils.bukkit.discordsrv.SlashCommandProvider.onCommand(SlashCommandProvider.java:72) [06:57:24 WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [06:57:24 WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) [06:57:24 WARN]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [06:57:24 WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:568) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.api.ApiManager.invokeMethod(ApiManager.java:344) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.api.ApiManager.handleSlashCommandEvent(ApiManager.java:319) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.api.ApiManager.onSlashCommand(ApiManager.java:293) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:483) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.handleEvent(JDAImpl.java:159) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.InteractionCreateHandler.handleCommand(InteractionCreateHandler.java:75) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:59) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.main(ReadingThread.java:108) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.runMain(ReadingThread.java:64) [06:57:24 WARN]: at DiscordSRV-Build-1.26.2.jar//github.scarsz.discordsrv.dependencies.ws.client.WebSocketThread.run(WebSocketThread.java:45)

There must be an earlier error, look for errors around server startup

**Comment by games4681** [comment]
solved.

**Comment by BlueTree242** [comment]
Can you please mention how you solved it? Other people may have the same issue and might find it helpful
