### ISSUE TITLE
add support to new version of discordsrv

### ISSUE THREAD

**Issue by games4681** [BlueTree242/DiscordSRVUtils#154]
this error spam the console:
![1](https://github.com/BlueDevelopersInc/DiscordSRVUtils/assets/102223894/2e5f996a-b6dd-4e67-878a-c9a1a80aabce)

**Comment by Stikulzon** [comment]
Same problem
```
- [Thu 14:58:16 ERROR DiscordSRV] [JDA] One of the EventListeners had an uncaught exception
java.lang.IncompatibleClassChangeError: Found interface github.scarsz.discordsrv.objects.managers.AccountLinkManager, but class was expected
    at Plan-5.5-build-2391.jar//net.playeranalytics.extension.discordsrv.DiscordSRVListener.updateUser(DiscordSRVListener.java:71)
    at Plan-5.5-build-2391.jar//net.playeranalytics.extension.discordsrv.DiscordSRVListener.onGuildMemberRoleAdd(DiscordSRVListener.java:96)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:483)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.handleEvent(JDAImpl.java:159)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.entities.EntityBuilder.updateMemberRoles(EntityBuilder.java:699)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.entities.EntityBuilder.updateMember(EntityBuilder.java:592)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.GuildMemberUpdateHandler.handleInternally(GuildMemberUpdateHandler.java:63)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
    at DiscordSRV-Build-1.27.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
    at DiscordSRV-Build-1.27.0.jar//github.scar
```
