### ISSUE TITLE
Not compatible with DiscordSRV v1.24.0

### ISSUE THREAD

**Issue by BoredManCodes** [BlueTree242/DiscordSRVUtils#61]
Users running the latest release are receiving this error
`	[12:39:22] [JDA MainWS-ReadThread/ERROR]: [DiscordSRV] [JDA] One of the EventListeners had an uncaught exception
java.lang.NoSuchMethodError: 'boolean github.scarsz.discordsrv.dependencies.jda.api.entities.User.isFake()'
	at DiscordSRVUtils-1.1.13.jar//tech.bedev.discordsrvutils.events.JDAEvents.onGuildMessageReceived(JDAEvents.java:200)
	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:482)
	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.handleEvent(JDAImpl.java:160)
	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:97)
	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991)
	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.main(ReadingThread.java:108)
	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at DiscordSRV-Build-1.24.0.jar//github.scarsz.discordsrv.dependencies.ws.client.WebSocketThread.run(WebSocketThread.java:45)
[12:39:23] [JDA MainWS-ReadThread/ERROR]: [DiscordSRV] [JDA] One of the EventListeners had an uncaught exception`

**Comment by BlueTree242** [comment]
Its already fixed in the beta version, you will have to wait until its offically released or use it in its beta state. Or you can make your own fork

**Comment by BlueTree242** [comment]
Ohhh the master branch have the beta, my bad.... I think the only way is currently using the new beta
